python scenariogenerator.py ss 5
python scenariogenerator.py ss 10
python scenariogenerator.py ss 15
python scenariogenerator.py ss 20
python scenariogenerator.py ss 25
python scenariogenerator.py ss 30
python scenariogenerator.py ss 35
python scenariogenerator.py ss 45
python scenariogenerator.py ss 50
python scenariogenerator.py ss 55
python scenariogenerator.py ss 60
python scenariogenerator.py ss 65
python scenariogenerator.py ss 70
python scenariogenerator.py ss 75
python scenariogenerator.py ss 85
python scenariogenerator.py ss 90
python scenariogenerator.py ss 95


python scenariogenerator.py slr 1
python scenariogenerator.py slr 5
python scenariogenerator.py slr 10
python scenariogenerator.py slr 15
python scenariogenerator.py slr 20
python scenariogenerator.py slr 25
python scenariogenerator.py slr 30
python scenariogenerator.py slr 35
python scenariogenerator.py slr 40
python scenariogenerator.py slr 45
python scenariogenerator.py slr 50
python scenariogenerator.py slr 55
python scenariogenerator.py slr 60
python scenariogenerator.py slr 65
python scenariogenerator.py slr 70
python scenariogenerator.py slr 75
python scenariogenerator.py slr 80
python scenariogenerator.py slr 85
python scenariogenerator.py slr 90
python scenariogenerator.py slr 95
python scenariogenerator.py slr 98
